/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';

import Main from '../Components/Main.js';
import Script from 'next/script';

export default function Home() {
  return (
    <>
      <Head>
        <title>Chá das Marias</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/milk-bottle.png" type="image/png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Crafty+Girls&family=Gluten:wght@200&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Main></Main>
    </>
  );
}
