import Head from 'next/head';

import Main from '../Components/Main.js';
import Script from 'next/script';

export default function Home() {
  return (
    <>
      <Head>
        <title>Chá das Marias</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/milk-bttle.png" type="image/x-icon" />
      </Head>
      <Main></Main>
    </>
  );
}
